/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.poketrirx.crosswordlesolver;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {}
}
